from typing import Protocol


class WorkerProvider(Protocol):
    """Host-side lifecycle contract. Implementations never accept host shell commands."""

    def close(self) -> None: ...
    def check_resources(self, rows: list[dict], desired: dict) -> None: ...
    def create(self, row: dict) -> dict: ...
    def status(self, row: dict) -> dict: ...
    def start(self, row: dict) -> dict: ...
    def stop(self, row: dict) -> bool: ...
    def destroy(self, row: dict) -> dict: ...
    def reset(self, row: dict, generation: str) -> dict: ...
    def snapshot(self, row: dict, identifier: str) -> tuple[dict, dict]: ...
    def restore(self, row: dict, snapshot: dict) -> dict: ...
    def execute(self, row: dict, identifier: str, script: str, timeout: int) -> dict: ...
